### ISSUE TITLE
issue: Setting up prisma formatting

### ISSUE THREAD

**Issue by ywwa** [stevearc/conform.nvim#110]
Im trying to setup prisma file formatting using [Prisma/prisma](https://github.com/prisma/prisma)
At first it formats but after that the content in neovim gets replaced by `prisma format` response message 
Preview video: 

https://github.com/stevearc/conform.nvim/assets/56758452/d5020524-2eec-4826-a3ba-aca0401e5d41

**Comment by stevearc** [comment]
By default conform will sent the text to the formatter via stdin, and will use the stdout as the new text of the file. It looks like `prisma format` doesn't support formatting stdin, so you'll need to set `stdin = false` which will instead write a temp file, run the formatter on the temp file, then read back the new contents of the temp file.

**Comment by ywwa** [comment]
setting `stdin` to `false` fixes issue at some level
but these still persists issue that after leaving insert mode file gets formatted in background and that prevents to save new changes

and formatting without any changes do not automatically update content in buffer i have to reopen file to see formatted version

**Comment by stevearc** [comment]
> after leaving insert mode file gets formatted in background and that prevents to save new changes

That sounds like an issue with your config. Conform doesn't do any formatting by default, much less format on `InsertLeave`. Also, the async formatting should discard any changes if you concurrently modify the buffer, so it should prevent anything.

> formatting without any changes do not automatically update content in buffer i have to reopen file to see formatted version

I have never seen this problem. Because of how formatting works, it shouldn't be possible. Feel free to file a bug if you can get a minimal repro, or you can set `log_level = vim.log.levels.TRACE` and debug it yourself.

**Comment by ywwa** [comment]
tried to reproduce my issue with `kickstart.nvim` config and problems nowhere to be found
