### ISSUE TITLE
bug: formatting with lua-language-server rewrites the whole buffer

### ISSUE THREAD

**Issue by AyushRawal** [stevearc/conform.nvim#119]
### Neovim version (nvim -v)

0.9.2

### Operating system/version

arch linux

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

17:45:28[DEBUG] Running LSP formatter on /home/rawal/.config/nvim/lua/user/plugins.lua
17:45:32[DEBUG] Running LSP formatter on /home/rawal/.config/nvim/lua/user/plugins.lua

### Describe the bug

same

### Steps To Reproduce

1. install lua language server
2. format with lsp_fallback = true
3. the whole buffer is written, even if there's no change

### Expected Behavior

only formatted lines should have been written

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

this issue does not happen with clangd

**Comment by stevearc** [comment]
You say "the whole buffer is written, even if there's no change" and the expected behavior is "only formatted lines should have been written"

So...were there formatting changes or not? Is the issue that the buffer gets set as modified after every run, even when nothing visibly changed? Does the same thing happen if you use `vim.lsp.buf.format()`?

**Comment by AyushRawal** [comment]
I am sorry for not stating it clearly. Yes, the buffer gets set as modified, even when nothing visibly changed. And yes, the same thing happens with `vim.lsp.buf.format()`.

**Comment by stevearc** [comment]
If you see the same behavior from `vim.lsp.buf.format()` then there's probably nothing we can do. It's the behavior of the language server itself.

**Comment by AyushRawal** [comment]
I am sorry if I misunderstood, but in README, one of the features mentioned is:

> Fixes bad-behaving LSP formatters - Some LSP servers are lazy and simply replace the entire buffer, leading to the problems mentioned above. Conform hooks into the LSP handler and turns these responses into proper piecewise changes.

That's why I filed this issue. Can you please clarify ?

**Comment by stevearc** [comment]
Ah, you are correct. I thought this would be happening because of the LSP sending some small no-op TextEdit on save, but yes it was replacing the entire buffer. The TextEdit was in a slightly different format from the other bad-behaving language server that I tested against, so we didn't catch it. I've updated the logic and it should work as expected now.
