### ISSUE TITLE
Feature request: toggling auto-format

### ISSUE THREAD

**Issue by willothy** [stevearc/conform.nvim#122]
Format-on-save is very useful, but it can be frustrating when working in projects without formatter configs, as I end up messing up the formatting or needing to use `noautocmd write` to avoid triggering auto-format. Would be nice to have user commands to enable and disable auto-format, similar to [`lsp-format`](https://github.com/lukas-reineke/lsp-format.nvim) which has `FormatDisable`/`FormatEnable`/`FormatToggle`. I am open to contributing a PR for this, just figured I'd open an issue first to see if there's interest.

**Comment by stevearc** [comment]
This is in the category of things that I don't think make sense to add to the base plugin because of the vast amount of small variations that people may want in configuration and behavior. It's pretty easy to add this behavior yourself, tailored to your needs: https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#command-to-toggle-format-on-save

**Comment by willothy** [comment]
Sounds good, thanks!
