### ISSUE TITLE
feat: allow non-executables as command as well for formatters

### ISSUE THREAD

**Issue by gstokkink** [stevearc/conform.nvim#152]
FIrst of all, thanks for this excellent plugin, I like it a lot! I moved over from formatter.nvim, which isn't as powerful as this plugin.

I'm running into an issue when trying to define a non-executable as command for a formatter. For instance, I would like to use `bundle exec rubocop` as command for the Rubocop formatter (this is very common in the Ruby world, prefixing with `bundle exec`), but the `vim.fn.executable(cmd)` check used in the initializer will return `0` for such a command: https://github.com/stevearc/conform.nvim/blob/master/lua/conform/init.lua#L627.

As a workaround, I have added a simple bash script in my path that calls `bundle exec rubocop $*`, and then use that bash script as command for the formatter. Not ideal 😉

**Comment by stevearc** [comment]
The executable check is just so we can gracefully ignore formatters that you may not have installed, or may not be installed for a particular directory. It's unfortunate that ruby has this `bundle exec` pattern because it makes it difficult for us to check if the tool is available or not. You'll lose that nice property, but the way to handle this is to set the command to be `bundle` and then add `{ "exec", "rubocop" }` to the args

**Comment by gstokkink** [comment]
Thanks, that will do nicely as well 🙂
