### ISSUE TITLE
Feature request: globally set require_cwd

### ISSUE THREAD

**Issue by jackfranklin** [stevearc/conform.nvim#160]
Perhaps I am in the minority, but I would like to set require_cwd globally to be always true for all formatters.

I have worked around this by setting the flag on each formatter I use but it adds a bit of noise to my config.

Would you accept a PR that does this? Happy to work on this if so. Thanks!

**Comment by stevearc** [comment]
Having `require_cwd = false` by default is actually the intended behavior. For example, when I'm editing a python file, I want to run the formatter in its package directory when I can so that [black](https://github.com/stevearc/conform.nvim/blob/master/lua/conform/formatters/black.lua) can pick up on its configuration options. However, if I'm just editing a standalone python script, I _still_ want black to run even though there's no `pyproject.toml` file.
