### ISSUE TITLE
feat: Command to disable formatting

### ISSUE THREAD

**Issue by BitInByte** [stevearc/conform.nvim#192]
Hello @stevearc and all maintainers, thanks for the amazing work, not only on conform.nvim but also on oil.nvim which I heavily use them. 

Would it be possible to add a command to conform to disable the format on save? I used that a lot with null-ls, sometimes my formatting rules are different than the repo rules and sometimes I get a diff on git logs just for formatting changes and what I was doing in this cases on null-ls were disabling the formatting, save the file and then enabling the formatting again.

Would it be possible to do with conform as well?

Thanks in advance :D

**Comment by stevearc** [comment]
I don't think this makes sense to add to the core plugin, but it's easy enough to add this logic yourself! https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#command-to-toggle-format-on-save

**Comment by andradei** [comment]
Wanting to write a buffer without formatting is a valid use-case. Specially when you're working on a code base in a team and you don't want your formatter to change the entire file because a line change you had to make.

**Comment by breakingram** [comment]
Here is my auto-format toggle config:

`<leader>tf` - will toggle per‑buffer autoformat
`<leader>tF` - will toggle global autoformat

```lua
return { -- Autoformat
  'stevearc/conform.nvim',
  lazy = false,
  keys = {
    {
      '<leader>tf',
      function()
        -- If autoformat is currently disabled for this buffer,
        -- then enable it, otherwise disable it
        if vim.b.disable_autoformat then
          vim.cmd 'FormatEnable'
          vim.notify 'Enabled autoformat for current buffer'
        else
          vim.cmd 'FormatDisable!'
          vim.notify 'Disabled autoformat for current buffer'
        end
      end,
      desc = 'Toggle autoformat for current buffer',
    },
    {
      '<leader>tF',
      function()
        -- If autoformat is currently disabled globally,
        -- then enable it globally, otherwise disable it globally
        if vim.g.disable_autoformat then
          vim.cmd 'FormatEnable'
          vim.notify 'Enabled autoformat globally'
        else
          vim.cmd 'FormatDisable'
          vim.notify 'Disabled autoformat globally'
        end
      end,
      desc = 'Toggle autoformat globally',
    },
  },
  opts = {
    notify_on_error = false,
    format_on_save = function(bufnr)
      if vim.g.disable_autoformat or vim.b[bufnr].disable_autoformat then
        return
      end
      local disable_filetypes = { c = false, cpp = false }
      return {
        timeout_ms = 500,
        lsp_fallback = not disable_filetypes[vim.bo[bufnr].filetype],
      }
    end,
    formatters_by_ft = {
      lua = { 'stylua' },
      python = { 'black' },
      javascript = { { 'prettierd', 'prettier' } },
      typescript = { { 'prettierd', 'prettier' } },
      typescriptreact = { { 'prettierd', 'prettier' } },
      javascriptreact = { { 'prettierd', 'prettier' } },
      css = { { 'prettierd', 'prettier' } },
      cs = { 'csharpier' },
    },
  },
  config = function(_, opts)
    require('conform').setup(opts)

    vim.api.nvim_create_user_command('FormatDisable', function(args)
      if args.bang then
        -- :FormatDisable! disables autoformat for this buffer only
        vim.b.disable_autoformat = true
      else
        -- :FormatDisable disables autoformat globally
        vim.g.disable_autoformat = true
      end
    end, {
      desc = 'Disable autoformat-on-save',
      bang = true, -- allows the ! variant
    })

    vim.api.nvim_create_user_command('FormatEnable', function()
      vim.b.disable_autoformat = false
      vim.g.disable_autoformat = false
    end, {
      desc = 'Re-enable autoformat-on-save',
    })
  end,
}

```

**Comment by rijulkap** [comment]
Here's how to go about it if you want to use the Snacks.nvim toggle:

```
return {
    { 
        "stevearc/conform.nvim",
        event = { "BufWritePre" },
        opts = function()
            return {
                format_on_save = function(bufnr)
                    if vim.g.autoformat then
                        local disable_filetypes = {}
                        local lsp_format_opt
                        if disable_filetypes[vim.bo[bufnr].filetype] then
                            lsp_format_opt = "never"
                        else
                            lsp_format_opt = "fallback"
                        end
                        return {
                            timeout_ms = 500,
                            lsp_format = lsp_format_opt,
                        }
                    else
                        return
                    end
                end,
            }
        end,
    },
    { -- Assuming you init/setup snacks.nvim in a different file 
        "folke/snacks.nvim",
        opts = function()
            vim.g.autoformat = true  -- Sets up the default value to be true

            Snacks.toggle
                .new({
                    id = "Format on Save",
                    name = "Format on Save",
                    get = function()
                        return vim.g.autoformat
                    end,
                    set = function(_)
                        vim.g.autoformat = not vim.g.autoformat
                    end,
                })
                :map("<leader>uf")
        end,
    },
}
```

**Comment by ethanuppal** [comment]
The provided recipe does not appear to work in my setup; in particular, conform does not seem to respect the global variable these commands set.

**Comment by stevearc** [comment]
I will weigh in on this once more since from the reactions it appears a lot of people do want this to be a feature.

Let me lead with the most useful information: if you find yourself editing a file and you are fighting with the autoformatter, there is a simple escape hatch: `:noau w`. You can put `:noau` before any command and it will run that command _without_ triggering autocmds. In this case, it will write the buffer without the `BufWritePre` and `BufWritePost` autocmds that trigger autoformatting. If you need to do this more than 2 or 3 times it can get tedious, which is why at this point I would recommend the recipe I linked as a way to disable it in a more durable fashion.

Why not provide a built-in way to disable autoformatting? I could, for example, add an API call that would disable the `format_on_save/format_after_save` operations. Let's call that `conform.toggle_autoformat()` and look at that config:

```lua
require("conform").setup({
  format_on_save = function(bufnr)
    return { timeout_ms = 500, lsp_format = "fallback" }
  end,
})
```

Then, if you find a situation where you want to disable autoformatting, you would call `lua require("conform").toggle_autoformat()`. Cool. Okay how does it work right now? You have to write this config:

```lua
require("conform").setup({
  format_on_save = function(bufnr)
    if vim.g.disable_autoformat then
      return
    end
    return { timeout_ms = 500, lsp_format = "fallback" }
  end,
})
```
And whenever you want to disable autoformatting, you do `:lua vim.g.disable_autoformat = true`. So we save...3 lines of config, at the cost of adding more API methods. "Doesn't seem like such a big cost," you say. "This is a very simple method, what could it hurt?"

For something like this, eventually people will ask for more features. They'll want a way to provide a boolean to specify enabled or disabled. Very reasonable.

```lua
conform.toggle_autoformat(enabled)
```

Then someone will ask for a way to do it for a specific buffer instead of globally. Also quite reasonable.

```lua
conform.toggle_autoformat(enabled, bufnr)
```

Then someone will be confused about the interaction between the two, because they disabled formatting on a buffer, but then they _enabled_ it globally, so why is formatting still disabled for that buffer? Shouldn't writing the global setting override any buffer-local settings? Maybe...maybe not. I can see it making sense either way. So now we have to provide some third config argument that allows specifying whether the global setting should override the buffer-local setting. Someone else wants to disable autoformatting by filetype. Someone else wants to disable autoformatting for specific formatters. Now the function looks like this:

```lua
conform.toggle_autoformat(enabled, bufnr, override_local_value, by_filetype, specific_formatters)
-- In reality we would have to refactor the function at this point to take an `opts` table
```

Now for a new user that just wants to disable autoformatting, they have to read and understand a much more complicated method signature to do something basic. What started as a mild convenience for the simple use case has turned into something too complex for the simple use case and _still_ not flexible enough to work for all power users.

This is why I have the bar set pretty high for adding more APIs. It needs to be something that either _cannot_ be achieved in user code, or something that is a relatively common need and requires either tricky or large amounts of code. Different people will have different thresholds for "common", "tricky", and "large amounts", and that's a discussion we can have (though ultimately, as the person with the maintenance burden, I will have the final say). This request, though common, squarely falls massively short of the "tricky code" and "large amounts of code" threshold for me.
