### ISSUE TITLE
Question: Use neovim command as formatter command

### ISSUE THREAD

**Issue by loganwishartcraig** [stevearc/conform.nvim#193]
Hi

I have a command supported by tsserver, `:OrganizeImports`, and I'd like to have this run for all javascript/typescript files. 

Is there any way to have a custom formatter `formatters.[name].command` reference a neovim command to run instead of a binary to execute?

Would be cool if so!

**Comment by stevearc** [comment]
Lua functions are technically supported as a formatter, but I go into some of the limitations in this comment https://github.com/stevearc/conform.nvim/issues/186#issuecomment-1804199512

Commands are even worse than functions, because they have no return value and (if they are async) we have no way of detecting when they are done. My recommendation would be to either set up a separate autocmd, or to run it manually when needed.

**Comment by loganwishartcraig** [comment]
Super helpful, thank you!
