### ISSUE TITLE
using lsp formatting on specific filetypes

### ISSUE THREAD

**Issue by perrin4869** [stevearc/conform.nvim#36]
I am trying to use lsp formatting on scala files, but avoid using lsp formatting on `typescript` files.
I have the following config:

```lua
local utils = require("utils")

require("conform").setup({
	formatters_by_ft = {
		lua = { "stylua" },
		javascript = { "eslint_d" },
		javascriptreact = { "eslint_d" },
		typescript = { "eslint_d" },
		typescriptreact = { "eslint_d" },
		-- Use a sub-list to run only the first available formatter
		json = { { "prettierd", "prettier" } },
		scala = {},
		["*"] = { "trim_whitespace" },
	},
})

local function format()
	require("conform").format({ lsp_fallback = true })
end

local function format_write()
	require("conform").format({
		lsp_fallback = true,
	}, vim.cmd.write)
end

local opts = { silent = true }
local get_opts = utils.create_get_opts(opts)
vim.keymap.set("n", "<leader>f", format, get_opts({ desc = "conform.format" }))
vim.keymap.set("n", "<leader>F", format_write, get_opts({ desc = "conform.format_write" }))

vim.api.nvim_create_autocmd("BufWritePost", {
	group = vim.api.nvim_create_augroup("FormatAutogroup", {}),
	callback = format_write,
})
```

If I run `format` on a `typescript` file with this config, `eslint_d` will format the file. On a scala file, nothing will happen.
If I replace `lsp_fallback = true -> "always"`, running `format` will run the lsp formatter on both scala and typescript.
There doesn't seem to be a way to specify running the lsp formatter on scala files, but not on typescript files?

**Comment by stevearc** [comment]
Here's my recommendation for changes:
```lua
local utils = require("utils")

local function get_lsp_fallback(bufnr)
  local always_use_lsp = not vim.bo[bufnr].filetype:match("^typescript")
  return always_use_lsp and "always" or true
end

local function format()
  require("conform").format({
    lsp_fallback = get_lsp_fallback(0),
    -- I would recommend setting async=true for this so formatting doesn't freeze the editor.
    -- Async formatting changes will be discarded if you modify the buffer before it's completed.
    -- async = true,
  })
end

-- I don't personally see the need for this; if you autoformat on save, this should be the same as
-- saving the buffer. But if you like it, keep it.
local function format_write()
  require("conform").format({
    lsp_fallback = true,
    -- same comment about setting async = true here
    -- async = true,
  }, function(err)
    if not err then
      vim.cmd.update()
    end
  end)
end

local opts = { silent = true }
local get_opts = utils.create_get_opts(opts)
vim.keymap.set("n", "<leader>f", format, get_opts({ desc = "conform.format" }))
vim.keymap.set("n", "<leader>F", format_write, get_opts({ desc = "conform.format_write" }))

require("conform").setup({
  formatters_by_ft = {
    lua = { "stylua" },
    javascript = { "eslint_d" },
    javascriptreact = { "eslint_d" },
    typescript = { "eslint_d" },
    typescriptreact = { "eslint_d" },
    json = { { "prettierd", "prettier" } },
    ["*"] = { "trim_whitespace" },
  },
  -- This option will handle creating the autocmd and saving for you
  format_after_save = function(bufnr)
    return {
      lsp_fallback = get_lsp_fallback(bufnr),
    }
  end,
})
```

**Comment by perrin4869** [comment]
Thanks! I think I got the behavior that I wanted now 😄
It would be slightly cooler if the lsp fallback could be more declarative but this will do just fine too

**Comment by MariaSolOs** [comment]
@stevearc about your advice of using `async = true`: Is there a difference between using `format_on_save` with `async = true` and using `format_after_save`?

**Comment by stevearc** [comment]
Yep! If you want to see what's going on behind the scenes, [the code is here](https://github.com/stevearc/conform.nvim/blob/dbf1d44404d4e0dcd23dcb94a5559ef0d0c424cc/lua/conform/init.lua#L83-L135). The difference is: `format_on_save` will actually _force_ async to be false. There are two reason for that:
1. It runs on BufWritePre. If it ran async then you would write the buffer to disk _before_ formatting completed. This is a particular problem in certain cases (e.g. format-save-exit with `:wq`)
2. Async formatting will discard the formatting changes if you have modified the buffer in between starting the formatter and getting the results back. We used `changedtick` for that. From `:help changedtick`

> b:changedtick	The total number of changes to the current buffer.  It is
		incremented for each change.  An undo command is also a change
		in this case.  **Resetting 'modified' when writing the buffer is
		also counted.**

This means that what would happen is you `:w`, we get a BufWritePre, kick off the async formatter, Neovim writes the file to disk and sets `modified = false`, that will _increment_ the `changedtick`, then we get the formatter response and it will discard the results because the `changedtick` mismatches.

`format_after_save` is provided for people that do want async formatting when saving the file. There's a bit more logic to it, but in brief: it kicks off the async format _after_ the file is written and modified is set to false (in `BufWritePost`). When it gets the results back, if you haven't modified the file in the meantime it will apply the changes and run `:update` for you, while setting a flag to make sure that the call to `:update` doesn't trigger another async format.

**Comment by MariaSolOs** [comment]
@stevearc thanks a lot for explaining! It clarifies a lot :)

I know that it depends on the use case, but do you have a personal recommendation on what to use? Format before/after save (it already sounds like you recommend `async = true` for the latter)?

**Comment by stevearc** [comment]
I personally use format on BufWritePre wherever I can. I think the `:wq` guarantees and general simplicity make it slightly preferable on average. However, if a formatter takes longer than about 500ms, that's too long of a freeze for me to tolerate so I use the async BufWritePost formatting. I control this with a [simple filetype check](https://github.com/stevearc/dotfiles/blob/597bd1337c527bbc13487ef096a4b4267cb37d8d/.config/nvim/lua/plugins/format.lua#L36-L49) in the callbacks.

**Comment by MariaSolOs** [comment]
@stevearc makes sense. Thanks again <3

**Comment by stevearc** [comment]
@perrin4869 I wasn't fully happy with the solution I gave you, so I changed the behavior in #59. Now you shouldn't need the `get_lsp_fallback` helper; passing in `lsp_fallback = true` should just do what you want.

As a side note, I did spend some time seeing if I could make it so that `"lsp"` is just another formatter you could put in the table, but I couldn't find a way to make it viable. The way LSP formatting works is just too different; I could make it work 95% of the time, but there would always be some edge cases with unexpected behavior.

**Comment by perrin4869** [comment]
Oh cool thanks for the heads up!! I'll update it to the new behavior, I think it's more intuitive, thanks!

I thought that lsp formatting can be expressed as an async function, I'm surprised to hear there are edge cases though... out of curiosity, what are the edge cases?

**Comment by stevearc** [comment]
Formatters are expressed as a function that takes in the lines of the original file and outputs the lines of the formatted file. This design is simple to understand and simple to handle because it's basically a pure function. You start with the input lines, pipe it through however many formatters, then take the result and turn it into diffs.

LSP formatting doesn't accept arbitrary input lines; it has to operate on the current state of the buffer. It also outputs a set of `TextEdit` changes instead of the lines for a formatted file. This means there are a lot of rough edges when you try to pipeline LSP formatting with other formatters.

I suppose I misspoke earlier, the issue is not that there are edge cases that _cannot_ be handled; I expect that with enough effort I could smooth it out. The issue is that in order to support any possible ordering and configuration of LSP and non-LSP formatting, I would have to write quite a bit of kludgy code to handle all of those cases. I think one of the strengths of this project as compared to some of my other plugins is that it's relatively simple. It's not an obvious decision, but right now it seems to me like the added complexity of creating that API does not provide enough value to justify it.
