### ISSUE TITLE
bug: With format_on_save, timeout_ms must be set really high to have prettier working

### ISSUE THREAD

**Issue by caneta** [stevearc/conform.nvim#401]
### Neovim version (nvim -v)

v0.10.0-dev

### Operating system/version

WSL (Windows Subsystem Linux), Ubuntu 20.04.6 LTS

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

```
15:14:08[DEBUG] Running formatters on /home/user/my-project/Test.tsx: { "prettier" }
15:14:08[INFO] Run prettier on /home/user/my-project/Test.tsx
15:14:08[DEBUG] Run command: { "/home/user/my-project/node_modules/.bin/prettier", "--stdin-filepath", "/home/user/my-project/Test.tsx" }
15:14:08[DEBUG] Run CWD: /home/user/my-project
15:14:09[WARN] Formatter 'prettier' timeout
15:14:09[INFO] prettier exited with code 143
15:14:09[DEBUG] prettier stdout: { "" }
15:14:09[DEBUG] prettier stderr: { "" }
```

### Describe the bug

I was expecting that the [suggested conf](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#setup) of 500 ms had worked just fine, but I had a timeout.
The same result setting `timeout_ms = nil`, or removing it (so getting the default 1 sec, I guess.
It seems that like just the `async` option is not set to `false` as documented.

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. nvim /hove/user/my-project/Test.tsx
2. mess up the file
3. :w

### Expected Behavior

I was expecting to have the file formatted by prettier and next saved by nvim. Only save succeed, and Conform reports the errors above. The only way to make it work is set to a very hight value like `timeout_ms = 999999`

**Comment by stevearc** [comment]
The default value of 500ms should be plenty of time for most formatters, and since formatting freezes the UI you probably don't want it to be larger than 500ms anyway. The quick fix for you that I would recommend is try using `format_after_save` instead of `format_on_save` (these are [documented here](https://github.com/stevearc/conform.nvim/?tab=readme-ov-file#options)).

Both `format_on_save` and `format_after_save` are just convenience wrappers that set up some autocmds for you. `format_on_save` uses a `BufWritePre` autocmd, which means that it executes in between the `:w` and Neovim actually writing the buffer to disk. For this reason, we _must_ complete the formatting synchronously and block all processing in the meantime, otherwise Neovim will write the unformatted buffer to disk while we are still formatting.

`format_after_save` uses the `BufWritePost` autocmd. After Neovim writes the buffer to disk, we try to format the file. This happens asynchronously and does not need to block the UI. Once formatting is completed, it applies the changes to the buffer and re-saves the buffer to disk. If the user has modified the buffer at all between formatting start and formatting completion, we abandon the changes (to avoid overwriting your edits).

When your formatter takes a long time to run, the recommended way to handle this is via async formatting (such as `format_after_save`).

**Comment by caneta** [comment]
Crystal-clear @stevearc, thank you so much for your detailed answer. It works like a charm!

**Comment by ic-768** [comment]
I was struggling with this same issue, and what fixed this for me was using `prettierd` instead of `prettier`. 
Much faster than `prettier`, and cleaner than running after save. 

```
    conform.setup({
      formatters_by_ft = {
        javascript = { "eslint_d","prettierd" },
        typescript = { "eslint_d","prettierd" },
      }
     })

```
