### ISSUE TITLE
bug:  WARNING prettier unavailable: Condition failed

### ISSUE THREAD

**Issue by godmode33** [stevearc/conform.nvim#490]
### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Ubuntu Mantic

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Not sure how to do that

### Describe the bug

Even though i have prettier available, and installed using volta, with volta install prettier, conform.nvim health check says:

conform: require("conform.health").check()

`WARNING prettier unavailable: Condition failed`

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

conform: require("conform.health").check()

### Expected Behavior

I expect for conform.nvim to be able to detect that the prettier executable is available.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
Please follow the bug report template and provide repro steps that work with the minimal init.lua configuration. The init.lua config does not include prettier at all, and the "condition failed" message will _never_ appear with the base config because there is no default condition function. You have likely either added a condition or are using a distribution that has added a condition to the formatter, but without seeing your config I can't help you.

**Comment by godmode33** [comment]
> Please follow the bug report template and provide repro steps that work with the minimal init.lua configuration. The init.lua config does not include prettier at all, and the "condition failed" message will _never_ appear with the base config because there is no default condition function. You have likely either added a condition or are using a distribution that has added a condition to the formatter, but without seeing your config I can't help you.

Yes i am using lazyvim: https://www.lazyvim.org/extras/formatting/prettier

I will have to look into it, as i am unfamiliar with lua.

**Comment by stevearc** [comment]
Looks like LazyVim adds this condition to prettier
https://github.com/LazyVim/LazyVim/blob/150523b77b6e848c4135a97a5fd8f6f79a6f4443/lua/lazyvim/plugins/extras/formatting/prettier.lua#L78-L80

So something in that condition is returning false, which is why prettier is not running. I'm not familiar with what is going on there, so if you have questions you'll want to post on the LazyVim repo

**Comment by LevelbossMike** [comment]
For anybody coming to this issue because of lazyvim: [this](https://github.com/LazyVim/LazyVim/discussions/4068#discussioncomment-10199757) might help you
