### ISSUE TITLE
feature request: Make range to be automatically detected in visual and visual line mode when doing range formatting.

### ISSUE THREAD

**Issue by 231tr0n** [stevearc/conform.nvim#556]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

```lua
	vim.api.nvim_create_user_command("Format", function(args)
		local range = nil
		if args.count ~= -1 then
			local end_line = vim.api.nvim_buf_get_lines(0, args.line2 - 1, args.line2, true)[1]
			range = {
				start = { args.line1, 0 },
				["end"] = { args.line2, end_line:len() },
			}
		end
		require("conform").format({ async = true, range = range })
	end, { range = true })
```
Without manually calculating the range, is it possible for the format function to calculate the range automatically when in visual or visual-line mode.

### Provide background

Currently I am manually providing the range and without manually providing the range the formatter seems to not work even though it is mentioned as such in docs.

### What is the significance of this feature?

nice to have

### Additional details

None

**Comment by 231tr0n** [comment]
Ok nvm, I had to map a keybinding in visual mode to do this. I am really sorry for raising this false request.

**Comment by 231tr0n** [comment]
Ok update again, even with visual mode keybind it is still the same.

**Comment by stevearc** [comment]
We do automatically fetch the range from the visual selection when `format` is called in visual mode
https://github.com/stevearc/conform.nvim/blob/1a99fdc1d3aa9ccdf3021e67982a679a8c5c740c/lua/conform/init.lua#L448-L451

What's tripping you up is when you're in visual mode and type `:` the command prepopulates with `:'<,'>`, which will pass a range to the command that uses the marks defined by the _previous_ visual selection (see `:help '<`). That means that when you run the command, it will first _exit_ visual mode and then call the function. So you are leaving visual mode before calling `conform.format`, which is why it cannot automatically get the range.

**Comment by 231tr0n** [comment]
> We do automatically fetch the range from the visual selection when `format` is called in visual mode
> 
> https://github.com/stevearc/conform.nvim/blob/1a99fdc1d3aa9ccdf3021e67982a679a8c5c740c/lua/conform/init.lua#L448-L451
> 
> What's tripping you up is when you're in visual mode and type `:` the command prepopulates with `:'<,'>`, which will pass a range to the command that uses the marks defined by the _previous_ visual selection (see `:help '<`). That means that when you run the command, it will first _exit_ visual mode and then call the function. So you are leaving visual mode before calling `conform.format`, which is why it cannot automatically get the range.

I had one last doubt, like how can I make the above command to work for range without passing range manually in that case. I was having a hard time figuring it out.
