### ISSUE TITLE
Confused about setting `formatters_by_ft` and returning a table from `format_on_save`

### ISSUE THREAD

**Issue by MariaSolOs** [stevearc/conform.nvim#565]
Not a bug but a question!

As the title says, I don't understand the difference between the configuration in `formatters_by_ft` and the return value of `format_on_save`. For reference, I'm trying to configure LSP formatting in some filetypes only and use other CLIs (like `stylua`) in other cases.

However I'm confused as of why I seem to need to have both properties match. As an example, if remove `formatters_by_ft` below, then `stylua` and `shfmt` aren't used by conform.

And so for my own learning, what should I configure in `formatters_by_ft` versus return from `format_on_save`?

Here's my full configuration:

```lua
-- Formatting.
local lang_settings = {
    c = { name = 'clangd', timeout_ms = 500, lsp_format = 'prefer' },
    javascript = { 'prettier', name = 'dprint', timeout_ms = 500, lsp_format = 'fallback' },
    json = { name = 'dprint', timeout_ms = 500, lsp_format = 'prefer' },
    jsonc = { name = 'dprint', timeout_ms = 500, lsp_format = 'prefer' },
    lua = { 'stylua' },
    rust = { name = 'rust_analyzer', timeout_ms = 500, lsp_format = 'prefer' },
    sh = { 'shfmt' },
    typescript = { 'prettier', name = 'dprint', timeout_ms = 500, lsp_format = 'fallback' },
}
return {
    {
        'stevearc/conform.nvim',
        event = 'BufWritePre',
        opts = {
            formatters_by_ft = lang_settings,
            format_on_save = function(bufnr)
                -- Stop if we haven't configured the buffer for auto-formatting.
                if not vim.b[bufnr].format_on_save then
                    return
                end

                return lang_settings[vim.bo[bufnr].ft]
            end,
        },
        init = function()
            -- Use conform for gq.
            vim.o.formatexpr = "v:lua.require'conform'.formatexpr()"

            -- Configure format on save inside my dotfiles and personal projects.
            vim.api.nvim_create_autocmd('BufEnter', {
                desc = 'Configure format on save',
                callback = function(args)
                    local path = vim.api.nvim_buf_get_name(args.buf)
                    path = vim.fs.normalize(path)
                    vim.b[args.buf].format_on_save = vim.iter({ vim.env.XDG_CONFIG_HOME, vim.g.personal_projects_dir })
                        :any(function(folder)
                            return vim.startswith(path, vim.fs.normalize(folder))
                        end)
                end,
            })
        end,
    },
}
```

**Comment by MariaSolOs** [comment]
Never mind, I think I get it now :) The options returned by `format_on_save` are merged with the ones in `formatter_by_ft` when calling `conform.format()`.

**Comment by stevearc** [comment]
`formatters_by_ft` is intended to provide default values based on filetype. It's effectively `conform.default_format_opts`, but also allows providing a list of formatters. Both of these provide default values for when you call `conform.format`, whether directly, from the `formatexpr`, or from `format_on_save`. The main use case for these is to create a default set of formatters & formatting options to use for a given filetype that will be consistent across the various places you call the formatting from (formatexpr, keymaps, commands, BufWritePre).

When you return values from `format_on_save`, those are passed directly in to `conform.format`, and will thus _override_ anything that was provided in the `formatters_by_ft` or `default_format_opts`. The main use case for customizing this is when you want to change something specifically only when formatting is being run on save.

There are some limitations for exactly what options can be provided by `formatters_by_ft` and `default_format_opts`. They only support `timeout_ms`, `lsp_format`, `quiet`, and `stop_after_first` (we actually don't support `name`, which you're currently using, but could add support for that easily). By contrast, `format_on_save` can provide _any_ valid option to `conform.format`.

Looking at what your config is trying to accomplish, I think you actually don't need to be returning `lang_settings[vim.bo[bufnr].ft]` from `format_on_save`. If you just return `{}` it should use the values set in `formatters_by_ft` (although not the `name`, as mentioned above). As for why formatting doesn't work when you exclude `formatters_by_ft`, that's because the structure of `formatters_by_ft` is _slightly_ different from what is passed in to `conform.format`. Notably, `formatters_by_ft` uses a hybrid table format that is list-like to define the formatters, but with string keys to define default options (e.g. `{ "prettier", timeout_ms = 500 }`). The signature for `conform.format` takes in an options table that expects the formatters to be passed in as a list under the `formatters` key (e.g. `{ formatters = { "prettier" }, timeout_ms = 500 }`). So when you remove `formatters_by_ft` and only pass in those values via format_on_save, it doesn't find the list of formatters you want to run.

**Comment by stevearc** [comment]
Added support for `name`, `id`, and `filter` in the `formatters_by_ft` config

**Comment by MariaSolOs** [comment]
@stevearc oh my thank you SO MUCH for the complete response and follow-up change! I understand much better now :)

In addition to the high quality of your plugins, it's interactions like this one that make me love your projects <3
