### ISSUE TITLE
When all formatters for a buffer have `cond=false`, then a warning is printed every time.

### ISSUE THREAD

**Issue by folke** [stevearc/conform.nvim#85]
In LazyVim, I do LSP formatting myself and don't use the conform.nvim fallback for this.

Unfortunately, this means when all formatters are disabled (due to `cond=false`), I always get the warning below.

I know there's `quiet = true`, but that would ignore all errors as well, which is not something I want to do.

Any suggestions?

https://github.com/stevearc/conform.nvim/blob/0cd34feae8b4a94271119a5d6a038f70c83582d1/lua/conform/init.lua#L376

**Comment by stevearc** [comment]
Hmmm...the original intention with this notification was for it to not trigger in cases that could be expected during normal operation, _especially_ if it could be repeated. Since it's possible to hit this branch when there's nothing actually wrong (formatter conditions returning false), I think it makes the most sense to just remove the notification entirely. It'll still go into the logfile as a warning and be visible in `:ConformInfo`.
