### ISSUE TITLE
bug: no formatter on save with custom formatter

### ISSUE THREAD

**Issue by petobens** [stevearc/conform.nvim#88]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-1240+g9afbfb4d64

### Operating system/version

Arch Linux

### Output of :ConformInfo

```
~ │Formatters for this buffer:                                                                                                                                                                                    │
~ │sqlfluff ready (sql)                                                                                                                                                                                           │
```

### Describe the bug

Formatter on save doesn't seem to work form custom formatter

### Steps To Reproduce

1. Open nvim with the minimal init.lua file provided
2. Open a `foo.sql` file with:
```sql
SELECT
  this_column,
  that_column as this_name,
  some_number * 10 AS a_bigger_number
FROM my_table
```
3.  Run `:w` to write -> nothing happens
4. Press `,fc` to run the format code -> the code is formatted

### Expected Behavior

After 3.  I would expect the code to get formatted.

### Minimal init.lua

```Lua
local root = '/tmp/nvim-minimal'

-- Set stdpaths to use root dir
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- Bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install and configure plugins
local plugins = {
    {
        'stevearc/conform.nvim',
        config = function()
            vim.o.formatexpr = [[v:lua.require('conform').formatexpr()]]
            require('conform').setup({
                format_on_save = {
                    timeout_ms = 200,
                    lsp_fallback = false,
                },
                notify_on_error = false,
                formatters = {
                    sqlfluff = {
                        command = 'sqlfluff',
                        args = {
                            'fix',
                            '--disable-progress-bar',
                            '-f',
                            '-n',
                            '-',
                        },
                        stdin = true,
                    },
                },
                formatters_by_ft = {
                    sql = { 'sqlfluff' },
                },
            })
            vim.keymap.set({ 'n', 'v' }, ',fc', function()
                require('conform').format({ async = true, lsp_fallback = false })
            end)
        end,
    },
}
require('lazy').setup(plugins, {
    root = root .. '/plugins',
})
```

### Additional context

![conformsql](https://github.com/stevearc/conform.nvim/assets/2583971/f4131e9d-f7d0-4e2a-8ca8-6af4d78faba5)

**Comment by petobens** [comment]
Extra help (sorry about that :) ): Is there a way for nvim-lint to play automatically with conform? In the following GIF I format the sqlfile on the right but the linter still shows errors after the file gets formatted (even though I have `TextChanged` event to run `try_lint`  as you can see on the left side). I need to save the file for the linter to pickup the change.

![conform_lint](https://github.com/stevearc/conform.nvim/assets/2583971/e1a17703-7e1e-4d8b-aa7b-00ecfe65cc69)

**Comment by stevearc** [comment]
When I reproduced it on my machine the reason why it failed to format on save was because it timed out. You will see the message if you run `:messages` or if you look at the logs in `:ConformInfo`. You can fix this by either increasing the timeout, or changing it to a `format_after_save` hook.

I recommend using [nvim-notify](https://github.com/rcarriga/nvim-notify), as it makes notifications more visible. In this case the one line with the timeout message is getting hidden by the `"foo.sql" written` message.

As for nvim-lint, I haven't had this sort of desyncing issue. Personally I do some debouncing when I trigger nvim-lint, so it's possible that's what makes the difference
https://github.com/stevearc/dotfiles/blob/04d4a05632e5b3e49d741be80a500f6d594ee1f3/.config/nvim/lua/plugins/lint.lua#L37-L57
But this is something that you would have to debug in nvim-lint. You would need to dig in and see what buffer content is actually being sent to the lint process, and if it's up-to-date.

**Comment by petobens** [comment]
Thanks for the pointers!
