### ISSUE TITLE
unable to open :ConformInfo

### ISSUE THREAD

**Issue by shaunstanislauslau** [stevearc/conform.nvim#95]
after typing `:ConformInfo`
i get an error  `Not an editor command: ConformInfo`

may i know where do i paste the formatter in too? do i need to create a file somewhere?

**Comment by stevearc** [comment]
My best guess is you are lazy loading the plugin but without specifying that the command `ConformInfo` should trigger the load. Impossible to say without seeing your config. Please follow the bug report template in the future; it will tell you how to create a minimal config file so that I can reproduce the problem you're having.

**Comment by shaunstanislauslau** [comment]
this is my config, you can view it [here](https://gist.github.com/shaunstanislauslau/45c6c7c39dc43bb6a24ab0c4d5fdbeae#file-init-vim-L98). what must i specify and where?

**Comment by stevearc** [comment]
You have to call `require("conform").setup()`. See the instructions in the README https://github.com/stevearc/conform.nvim#setup
